### ISSUE TITLE
cube correlation calculation dies without negative binning

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/pycorr#10]
Trying to calculate cube correlation (i.e., no randoms), if I try to plug in something natural like
edges = (np.linspace(0, 5, 21), np.linspace(0, 50, 51))
This line crashes
https://github.com/cosmodesi/pycorr/blob/81b4774dcd168de56c6785e80b26e78d02c45aad/pycorr/twopoint_estimator.py#L845

because self.R1R2.wcounts has shape (20,50) while self.D1D2.normalized_wcounts() is (20,100).
Ok, after figuring this out with the debugger I fixed it by extending radial bins negative, but it's ugly...

**Comment by adematti** [comment]
fixed in e5d1cc244561874e71c08e6ccc4987e3824b68e7
Note however that this is only for backward-compatibility purposes, and a warning will be issued, as the standard is now to provide `np.linspace(-50, 50, 101)`.
