### ISSUE TITLE
Incorrect error message at line 172 of twopoint_jackknife.py

### ISSUE THREAD

**Issue by jalasker** [cosmodesi/pycorr#11]
The error message at line 172 of twopoint_jackknife.py states (paraphrased) that the number of jackknife samples must be a power of ndim. My interpretation of that sentence is that if ndim = 3, valid numbers of subsamples would be 3**N =  3,9,27,81, etc. 

However, when I try all of those numbers (besides 27), I get the same error message.  

What I believe it should state is that the number of jackknife samples must an ndim-th power. This would mean that if ndim is 3, valid jknsamp would include N**3 = 8, 27, 64, 125, 216, etc. Those numbers do all successfully generate box jackknife samples.

**Comment by adematti** [comment]
Hi James, sorry for the delay!
Yes, that's totally correct --- would you like to submit a PR? or you can push a change directly!
Thanks!

**Comment by misharash** [comment]
I believe this is fixed (currently at line 177).
