### ISSUE TITLE
Feature request: method for (all) counts multiplication/division by a constant factor

### ISSUE THREAD

**Issue by misharash** [cosmodesi/pycorr#13]
Sometimes I need to multiply all counts in a `TwoPointEstimator` by a constant factor (most recently, for a quick computation of all the results for a concatenated catalog of two tracers, both data and randoms, with added relative weighting). This is achievable by calling the `normalize` method for all the count types and using their `wnorm` multiplied by the desired factor ([example 1](https://github.com/misharash/RascalC/blob/7bcd4a9c84fe62cf84b0d950472939c65848d9d3/python/convert_xi_jack_from_pycorr.py#L55), [example 2](https://github.com/misharash/RascalC/blob/7bcd4a9c84fe62cf84b0d950472939c65848d9d3/python/combine_covs_legendre_multi_to_cat.py#L75)), but this requires digging into the implementation a fair bit, and also in the process the new normalization is divided by `wnorm`. Would be nice to have a method to do this, or even an operator for multiplication by a floating-point number (although the latter could be confusing).

**Comment by adematti** [comment]
Hi, I have just added the operator * for counts, and applying e.g. * 2 to a `TwoPointEstimator` will multiply all its counts by 2. I have also updated the cosmodesi environment at NERSC. Let me know if that works for you.

**Comment by misharash** [comment]
Great, thank you, it works for both my use cases! In principle, the division operator might also be convenient, although it's pretty easy to recast as multiplication by inverse number.
